language: r
pandoc_version: 2.0.6
sudo: false
cache:
  packages: yes
  directories:
    - $HOME/bin
    - $TRAVIS_BUILD_DIR/inst/examples/_bookdown_files

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE" PATH=$HOME/bin:$PATH

repos:
  XRAN: https://xran.yihui.name

before_install:
  - "curl https://xran.yihui.name/.gitconfig -o ~/.gitconfig"
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"
  - export BUILD_ALL="$(git log --format=%B --no-merges -n 1 | grep -E "\[build all\]")"

before_script:
  - "[ -x \"$HOME/bin/phantomjs\" ] || Rscript -e \"webshot::install_phantomjs()\""
  - R CMD INSTALL .
  - cd inst/examples
  - "[ ! -z \"$BUILD_ALL\" ] && make all || make gitbook"
  - cd ../..

after_success:
  - "(curl https://xran.yihui.name/r-xran | bash)"
  - cd inst/examples; ./deploy_github
